import { Router } from 'express';
import { authenticate } from '../middleware/auth.js';
import { requireAdmin, requireAny } from '../middleware/rbac.js';
import { query, queryOne, queryAll } from '../config/database.js';
import { buildPaginationQuery, paginationMeta } from '../utils/helpers.js';
import { logAction, getClientIp } from '../services/auditService.js';
import supabaseAdmin from '../config/supabase.js';
import {
  saveEvaluationScores,
  submitEvaluation,
  reopenEvaluation,
  getTeamScores,
  getLeaderboard,
} from '../services/scoringService.js';

const router = Router();

/**
 * GET /api/evaluations/leaderboard
 * Authoritative leaderboard generated by PostgreSQL view v_leaderboard
 */
router.get('/leaderboard', authenticate, requireAny, async (req, res) => {
  try {
    const { page, limit, category, track, search } = req.query;
    const { limit: safeLimit, offset, page: safePage } = buildPaginationQuery(page, limit || 25);

    const { rows, total } = await getLeaderboard({
      category,
      track,
      search,
      limit: safeLimit,
      offset,
    });

    res.json({
      leaderboard: rows,
      pagination: paginationMeta(total, safePage, safeLimit),
    });
  } catch (error) {
    console.error('Leaderboard error:', error);
    res.status(500).json({ error: error.message || 'Failed to fetch authoritative leaderboard', code: 'INTERNAL_ERROR' });
  }
});

/**
 * GET /api/evaluations
 * Admin: all evaluations. Jury: own evaluations only.
 */
router.get('/', authenticate, requireAny, async (req, res) => {
  try {
    const { page, limit, status, team_id, user_id } = req.query;
    const { limit: safeLimit, offset, page: safePage } = buildPaginationQuery(page, limit);

    let where = [];
    let params = [];
    let paramIdx = 1;

    // Jury can only see own evaluations
    if (req.user.role === 'JURY') {
      where.push(`e.user_id = $${paramIdx}`);
      params.push(req.user.id);
      paramIdx++;
    } else if (user_id) {
      where.push(`e.user_id = $${paramIdx}`);
      params.push(user_id);
      paramIdx++;
    }

    if (status) {
      where.push(`e.status = $${paramIdx}`);
      params.push(status);
      paramIdx++;
    }
    if (team_id) {
      where.push(`e.team_id = $${paramIdx}`);
      params.push(team_id);
      paramIdx++;
    }

    const whereClause = where.length > 0 ? `WHERE ${where.join(' AND ')}` : '';

    try {
      const countResult = await queryOne(
        `SELECT COUNT(*) as count FROM evaluations e ${whereClause}`, params
      );
      const total = parseInt(countResult.count);

      const evaluations = await queryAll(
        `SELECT e.*, t.team_code, t.team_name, t.organization, t.category,
          u.full_name as judge_name, u.judge_id
         FROM evaluations e
         JOIN teams t ON e.team_id = t.id
         JOIN users u ON e.user_id = u.id
         ${whereClause}
         ORDER BY e.updated_at DESC
         LIMIT $${paramIdx} OFFSET $${paramIdx + 1}`,
        [...params, safeLimit, offset]
      );

      return res.json({
        evaluations,
        pagination: paginationMeta(total, safePage, safeLimit),
      });
    } catch (pgErr) {
      console.warn('Postgres query failed in GET /api/evaluations, falling back to Supabase REST:', pgErr.message);
      let queryBuilder = supabaseAdmin
        .from('evaluations')
        .select('*, teams(team_code, team_name, organization, category), users(full_name, judge_id)', { count: 'exact' });

      if (req.user.role === 'JURY') {
        queryBuilder = queryBuilder.eq('user_id', req.user.id);
      } else if (user_id) {
        queryBuilder = queryBuilder.eq('user_id', user_id);
      }
      if (status) {
        queryBuilder = queryBuilder.eq('status', status);
      }
      if (team_id) {
        queryBuilder = queryBuilder.eq('team_id', team_id);
      }

      queryBuilder = queryBuilder
        .order('updated_at', { ascending: false })
        .range(offset, offset + safeLimit - 1);

      const { data, count, error: supaErr } = await queryBuilder;
      if (supaErr) throw supaErr;

      const evaluations = (data || []).map(e => ({
        ...e,
        team_code: e.teams?.team_code,
        team_name: e.teams?.team_name,
        organization: e.teams?.organization,
        category: e.teams?.category,
        judge_name: e.users?.full_name,
        judge_id: e.users?.judge_id,
      }));

      return res.json({
        evaluations,
        pagination: paginationMeta(count || 0, safePage, safeLimit),
      });
    }
  } catch (error) {
    console.error('List evaluations error:', error);
    res.status(500).json({ error: error.message || 'Failed to list evaluations', code: 'INTERNAL_ERROR' });
  }
});

/**
 * GET /api/evaluations/team/:teamId
 * Get all evaluations for a specific team (admin only)
 * Aggregates are computed authoritatively in PostgreSQL (v_team_score_aggregates)
 */
router.get('/team/:teamId', authenticate, requireAdmin, async (req, res) => {
  try {
    let team = null;
    try {
      team = await queryOne('SELECT * FROM teams WHERE id = $1', [req.params.teamId]);
    } catch {
      const { data } = await supabaseAdmin.from('teams').select('*').eq('id', req.params.teamId).maybeSingle();
      team = data;
    }

    if (!team) {
      return res.status(404).json({ error: 'Team not found', code: 'NOT_FOUND' });
    }

    let evaluations = [];
    try {
      evaluations = await queryAll(
        `SELECT e.*, u.full_name as judge_name, u.judge_id
         FROM evaluations e
         JOIN users u ON e.user_id = u.id
         WHERE e.team_id = $1
         ORDER BY e.submitted_at DESC NULLS LAST`,
        [req.params.teamId]
      );

      for (const eval_ of evaluations) {
        eval_.scores = await queryAll(
          `SELECT es.*, sc.name as criteria_name, sc.max_score, sc.weight, sc.sort_order
           FROM evaluation_scores es
           JOIN scoring_criteria sc ON (COALESCE(es.criteria_id, es.criterion_id) = sc.id)
           WHERE es.evaluation_id = $1
           ORDER BY sc.sort_order`,
          [eval_.id]
        );
      }
    } catch (pgErr) {
      console.warn('Postgres query failed in GET /team/:teamId, falling back to Supabase REST:', pgErr.message);
      const { data: supaEvals } = await supabaseAdmin
        .from('evaluations')
        .select('*, users(full_name, judge_id)')
        .eq('team_id', req.params.teamId)
        .order('submitted_at', { ascending: false });

      evaluations = (supaEvals || []).map(e => ({
        ...e,
        judge_name: e.users?.full_name,
        judge_id: e.users?.judge_id,
      }));

      const { data: criteriaList } = await supabaseAdmin.from('scoring_criteria').select('*').order('sort_order');
      const critMap = new Map((criteriaList || []).map(c => [c.id, c]));
      for (const eval_ of evaluations) {
        const { data: supaScores } = await supabaseAdmin
          .from('evaluation_scores')
          .select('*')
          .eq('evaluation_id', eval_.id);
        eval_.scores = (supaScores || []).map(s => {
          const c = critMap.get(s.criteria_id || s.criterion_id);
          return {
            ...s,
            criteria_name: c?.name,
            criteria_description: c?.description,
            max_score: c?.max_score,
            weight: c?.weight,
            sort_order: c?.sort_order,
          };
        }).sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0));
      }
    }

    // Authoritative PostgreSQL statistics with fallback
    let stats = null;
    try {
      const teamAgg = await getTeamScores(team.id);
      stats = {
        totalJudges: evaluations.length,
        completedJudges: parseInt(teamAgg?.completed_judges || 0),
        averageScore: teamAgg?.aggregate_score !== null && teamAgg?.aggregate_score !== undefined ? parseFloat(teamAgg.aggregate_score).toFixed(2) : null,
        weightedAverageScore: teamAgg?.weighted_aggregate_score !== null && teamAgg?.weighted_aggregate_score !== undefined ? parseFloat(teamAgg.weighted_aggregate_score).toFixed(2) : null,
        highestScore: teamAgg?.highest_score !== null && teamAgg?.highest_score !== undefined ? parseFloat(teamAgg.highest_score).toFixed(2) : null,
        lowestScore: teamAgg?.lowest_score !== null && teamAgg?.lowest_score !== undefined ? parseFloat(teamAgg.lowest_score).toFixed(2) : null,
      };
    } catch {
      const completed = evaluations.filter(e => e.status === 'submitted');
      const scores = completed.map(e => parseFloat(e.total_score)).filter(s => !isNaN(s));
      stats = {
        totalJudges: evaluations.length,
        completedJudges: completed.length,
        averageScore: scores.length > 0 ? (scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(2) : null,
        weightedAverageScore: null,
        highestScore: scores.length > 0 ? Math.max(...scores).toFixed(2) : null,
        lowestScore: scores.length > 0 ? Math.min(...scores).toFixed(2) : null,
      };
    }

    res.json({ team, evaluations, stats });
  } catch (error) {
    console.error('Get team evaluations error:', error);
    res.status(500).json({ error: error.message || 'Failed to get evaluations', code: 'INTERNAL_ERROR' });
  }
});

/**
 * GET /api/evaluations/:id
 */
router.get('/:id', authenticate, requireAny, async (req, res) => {
  try {
    let evaluation = null;
    try {
      evaluation = await queryOne(
        `SELECT e.*, t.team_code, t.team_name, t.problem_statement_id, t.problem_statement_title,
          t.organization, t.category, t.track, t.team_leader, t.team_members,
          u.full_name as judge_name, u.judge_id
         FROM evaluations e
         JOIN teams t ON e.team_id = t.id
         JOIN users u ON e.user_id = u.id
         WHERE e.id = $1`,
        [req.params.id]
      );
    } catch (pgErr) {
      console.warn('Postgres query failed in GET /api/evaluations/:id, falling back to Supabase REST:', pgErr.message);
      const { data } = await supabaseAdmin
        .from('evaluations')
        .select('*, teams(*), users(full_name, judge_id)')
        .eq('id', req.params.id)
        .maybeSingle();
      if (data) {
        evaluation = {
          ...data,
          team_code: data.teams?.team_code,
          team_name: data.teams?.team_name,
          problem_statement_id: data.teams?.problem_statement_id,
          problem_statement_title: data.teams?.problem_statement_title,
          organization: data.teams?.organization,
          category: data.teams?.category,
          track: data.teams?.track,
          team_leader: data.teams?.team_leader,
          team_members: data.teams?.team_members,
          judge_name: data.users?.full_name,
          judge_id: data.users?.judge_id,
        };
      }
    }

    if (!evaluation) {
      return res.status(404).json({ error: 'Evaluation not found', code: 'NOT_FOUND' });
    }

    // Jury can only see own evaluations
    if (req.user.role === 'JURY' && evaluation.user_id !== req.user.id) {
      return res.status(403).json({ error: 'Access denied', code: 'FORBIDDEN' });
    }

    let scores = [];
    try {
      scores = await queryAll(
        `SELECT es.*, sc.name as criteria_name, sc.description as criteria_description,
          sc.max_score, sc.weight, sc.sort_order
         FROM evaluation_scores es
         JOIN scoring_criteria sc ON (COALESCE(es.criteria_id, es.criterion_id) = sc.id)
         WHERE es.evaluation_id = $1
         ORDER BY sc.sort_order`,
        [req.params.id]
      );
    } catch (pgErr) {
      console.warn('Postgres query failed for evaluation scores, falling back to Supabase REST:', pgErr.message);
      const { data: criteriaList } = await supabaseAdmin.from('scoring_criteria').select('*').order('sort_order');
      const critMap = new Map((criteriaList || []).map(c => [c.id, c]));
      const { data } = await supabaseAdmin
        .from('evaluation_scores')
        .select('*')
        .eq('evaluation_id', req.params.id);
      scores = (data || []).map(s => {
        const c = critMap.get(s.criteria_id || s.criterion_id);
        return {
          ...s,
          criteria_name: c?.name,
          criteria_description: c?.description,
          max_score: c?.max_score,
          weight: c?.weight,
          sort_order: c?.sort_order,
        };
      }).sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0));
    }

    evaluation.scores = scores;
    res.json({ evaluation });
  } catch (error) {
    console.error('Get evaluation error:', error);
    res.status(500).json({ error: error.message || 'Failed to get evaluation', code: 'INTERNAL_ERROR' });
  }
});

/**
 * POST /api/evaluations
 * Create or get existing draft evaluation for team+jury pair
 */
router.post('/', authenticate, requireAny, async (req, res) => {
  try {
    const { team_id } = req.body;
    const userId = req.user.id;

    if (!team_id) {
      return res.status(400).json({ error: 'team_id is required', code: 'VALIDATION_ERROR' });
    }

    // Verify team exists
    let team = null;
    try {
      team = await queryOne('SELECT * FROM teams WHERE id = $1', [team_id]);
    } catch (pgErr) {
      console.warn('Postgres query failed for team in POST /api/evaluations, falling back to Supabase REST:', pgErr.message);
      const { data } = await supabaseAdmin.from('teams').select('*').eq('id', team_id).maybeSingle();
      team = data;
    }
    if (!team) {
      return res.status(404).json({ error: 'Team not found', code: 'NOT_FOUND' });
    }

    // Jury: verify assignment
    if (req.user.role === 'JURY') {
      let assignment = null;
      try {
        assignment = await queryOne(
          'SELECT id FROM jury_assignments WHERE user_id = $1 AND team_id = $2',
          [userId, team_id]
        );
      } catch (pgErr) {
        console.warn('Postgres query failed for assignment check, falling back to Supabase REST:', pgErr.message);
        const { data } = await supabaseAdmin
          .from('jury_assignments')
          .select('id')
          .eq('user_id', userId)
          .eq('team_id', team_id)
          .maybeSingle();
        assignment = data;
      }

      if (!assignment) {
        // Automatically assign team to this jury member on-demand
        try {
          try {
            await query(
              'INSERT INTO jury_assignments (user_id, team_id, assigned_by) VALUES ($1, $2, $1) ON CONFLICT (user_id, team_id) DO NOTHING',
              [userId, team_id]
            );
          } catch {
            await supabaseAdmin.from('jury_assignments').upsert({
              user_id: userId,
              team_id,
              assigned_by: userId,
            }, { onConflict: 'user_id,team_id' });
          }
        } catch (assignErr) {
          console.warn('Auto-assign on evaluation create notice:', assignErr.message);
        }
      }
    }

    // Check for existing evaluation
    let evaluation = null;
    try {
      evaluation = await queryOne(
        'SELECT * FROM evaluations WHERE team_id = $1 AND user_id = $2',
        [team_id, userId]
      );
    } catch (pgErr) {
      console.warn('Postgres query failed for existing evaluation check, falling back to Supabase REST:', pgErr.message);
      const { data } = await supabaseAdmin
        .from('evaluations')
        .select('*')
        .eq('team_id', team_id)
        .eq('user_id', userId)
        .maybeSingle();
      evaluation = data;
    }

    if (evaluation) {
      // Return existing with scores
      let scores = [];
      try {
        scores = await queryAll(
          `SELECT es.*, sc.name as criteria_name, sc.description as criteria_description,
            sc.max_score, sc.weight, sc.sort_order
           FROM evaluation_scores es
           JOIN scoring_criteria sc ON (COALESCE(es.criteria_id, es.criterion_id) = sc.id)
           WHERE es.evaluation_id = $1
           ORDER BY sc.sort_order`,
          [evaluation.id]
        );
      } catch (pgErr) {
        const { data: criteriaList } = await supabaseAdmin.from('scoring_criteria').select('*').order('sort_order');
        const critMap = new Map((criteriaList || []).map(c => [c.id, c]));
        const { data: supaScores } = await supabaseAdmin
          .from('evaluation_scores')
          .select('*')
          .eq('evaluation_id', evaluation.id);
        scores = (supaScores || []).map(s => {
          const c = critMap.get(s.criteria_id || s.criterion_id);
          return {
            ...s,
            criteria_name: c?.name,
            criteria_description: c?.description,
            max_score: c?.max_score,
            weight: c?.weight,
            sort_order: c?.sort_order,
          };
        }).sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0));
      }
      evaluation.scores = scores;
      return res.json({ evaluation, isExisting: true });
    }

    // Create new draft
    try {
      evaluation = await queryOne(
        'INSERT INTO evaluations (team_id, user_id, status) VALUES ($1, $2, \'draft\') RETURNING *',
        [team_id, userId]
      );
    } catch (pgErr) {
      console.warn('Postgres insert failed for evaluation, falling back to Supabase REST:', pgErr.message);
      const { data, error: supaErr } = await supabaseAdmin
        .from('evaluations')
        .insert({ team_id, user_id: userId, status: 'draft' })
        .select()
        .single();
      if (supaErr) throw supaErr;
      evaluation = data;
    }

    // Initialize with all active criteria
    try {
      const criteria = await queryAll('SELECT id FROM scoring_criteria WHERE is_active = true ORDER BY sort_order');
      for (const c of criteria) {
        await query(
          `INSERT INTO evaluation_scores (evaluation_id, criteria_id, criterion_id, team_id, judge_id)
           VALUES ($1, $2, $2, $3, $4)
           ON CONFLICT (evaluation_id, criteria_id) DO NOTHING`,
          [evaluation.id, c.id, team_id, userId]
        );
      }
    } catch (pgErr) {
      console.warn('Postgres query failed for criteria init, falling back to Supabase REST:', pgErr.message);
      const { data: criteriaList } = await supabaseAdmin
        .from('scoring_criteria')
        .select('id')
        .eq('is_active', true)
        .order('sort_order');
      for (const c of (criteriaList || [])) {
        await supabaseAdmin.from('evaluation_scores').upsert({
          evaluation_id: evaluation.id,
          criteria_id: c.id,
          criterion_id: c.id,
          team_id,
          judge_id: userId,
        }, { onConflict: 'evaluation_id,criteria_id' });
      }
    }

    // Fetch with full score data
    let scores = [];
    try {
      scores = await queryAll(
        `SELECT es.*, sc.name as criteria_name, sc.description as criteria_description,
          sc.max_score, sc.weight, sc.sort_order
         FROM evaluation_scores es
         JOIN scoring_criteria sc ON (COALESCE(es.criteria_id, es.criterion_id) = sc.id)
         WHERE es.evaluation_id = $1
         ORDER BY sc.sort_order`,
        [evaluation.id]
      );
    } catch (pgErr) {
      const { data: criteriaList } = await supabaseAdmin.from('scoring_criteria').select('*').order('sort_order');
      const critMap = new Map((criteriaList || []).map(c => [c.id, c]));
      const { data: supaScores } = await supabaseAdmin
        .from('evaluation_scores')
        .select('*')
        .eq('evaluation_id', evaluation.id);
      scores = (supaScores || []).map(s => {
        const c = critMap.get(s.criteria_id || s.criterion_id);
        return {
          ...s,
          criteria_name: c?.name,
          criteria_description: c?.description,
          max_score: c?.max_score,
          weight: c?.weight,
          sort_order: c?.sort_order,
        };
      }).sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0));
    }
    evaluation.scores = scores;

    try {
      await logAction(userId, 'evaluation.created', 'evaluation', evaluation.id,
        { team_code: team.team_code }, getClientIp(req));
    } catch (logErr) {
      console.warn('Audit log error on evaluation creation:', logErr.message);
    }

    res.status(201).json({ evaluation, isExisting: false });
  } catch (error) {
    console.error('Create evaluation error:', error);
    res.status(500).json({ error: error.message || 'Failed to create evaluation', code: 'INTERNAL_ERROR' });
  }
});

/**
 * PUT /api/evaluations/:id
 * Save / autosave draft scores
 * Authoritatively calculated by PostgreSQL inside a transaction
 */
router.put('/:id', authenticate, requireAny, async (req, res) => {
  try {
    const updated = await saveEvaluationScores(
      req.params.id,
      req.body.scores,
      req.body.comments,
      req.user
    );
    res.json({ evaluation: updated, message: 'Draft scores saved successfully' });
  } catch (error) {
    console.error('Update evaluation error:', error);
    res.status(error.status || 500).json({
      error: error.message || 'Failed to update evaluation',
      code: error.code || 'INTERNAL_ERROR',
      field: error.field,
    });
  }
});

/**
 * POST /api/evaluations/:id/submit
 * Finalize and submit evaluation
 * Validates scores, locks evaluation, preserves history snapshot, and recalculates team aggregates
 */
router.post('/:id/submit', authenticate, requireAny, async (req, res) => {
  try {
    const { scores, comments } = req.body;
    // CRITICAL: If scores were passed directly with the submit request, save them first
    if (Array.isArray(scores) && scores.length > 0) {
      await saveEvaluationScores(req.params.id, scores, comments, req.user);
    }
    const result = await submitEvaluation(req.params.id, req.user, getClientIp(req));
    res.json({
      evaluation: result.evaluation,
      teamStats: result.teamStats,
      message: 'Evaluation submitted successfully',
    });
  } catch (error) {
    console.error('Submit evaluation error:', error);
    res.status(error.status || 500).json({
      error: error.message || 'Failed to submit evaluation',
      code: error.code || 'INTERNAL_ERROR',
      missing: error.missing,
    });
  }
});

/**
 * POST /api/evaluations/:id/reopen
 * Admin reopens a submitted evaluation
 * Preserves audit history snapshot, unlocks evaluation, and recalculates aggregates
 */
router.post('/:id/reopen', authenticate, requireAdmin, async (req, res) => {
  try {
    const result = await reopenEvaluation(req.params.id, req.user, req.body.reason, getClientIp(req));
    res.json({
      evaluation: result.evaluation,
      teamStats: result.teamStats,
      message: 'Evaluation reopened successfully',
    });
  } catch (error) {
    console.error('Reopen evaluation error:', error);
    res.status(error.status || 500).json({
      error: error.message || 'Failed to reopen evaluation',
      code: error.code || 'INTERNAL_ERROR',
    });
  }
});

export default router;
