import { Router } from 'express';
import { authenticate } from '../middleware/auth.js';
import { requireAdmin, requireAny } from '../middleware/rbac.js';
import { query, queryOne, queryAll } from '../config/database.js';
import { buildPaginationQuery, paginationMeta } from '../utils/helpers.js';
import { logAction, getClientIp } from '../services/auditService.js';
import {
  saveEvaluationScores,
  submitEvaluation,
  reopenEvaluation,
  getTeamScores,
  getLeaderboard,
} from '../services/scoringService.js';

const router = Router();

/**
 * GET /api/evaluations/leaderboard
 * Authoritative leaderboard generated by PostgreSQL view v_leaderboard
 */
router.get('/leaderboard', authenticate, requireAny, async (req, res) => {
  try {
    const { page, limit, category, track, search } = req.query;
    const { limit: safeLimit, offset, page: safePage } = buildPaginationQuery(page, limit || 25);

    const { rows, total } = await getLeaderboard({
      category,
      track,
      search,
      limit: safeLimit,
      offset,
    });

    res.json({
      leaderboard: rows,
      pagination: paginationMeta(total, safePage, safeLimit),
    });
  } catch (error) {
    console.error('Leaderboard error:', error);
    res.status(500).json({ error: 'Failed to fetch authoritative leaderboard', code: 'INTERNAL_ERROR' });
  }
});

/**
 * GET /api/evaluations
 * Admin: all evaluations. Jury: own evaluations only.
 */
router.get('/', authenticate, requireAny, async (req, res) => {
  try {
    const { page, limit, status, team_id, user_id } = req.query;
    const { limit: safeLimit, offset, page: safePage } = buildPaginationQuery(page, limit);

    let where = [];
    let params = [];
    let paramIdx = 1;

    // Jury can only see own evaluations
    if (req.user.role === 'JURY') {
      where.push(`e.user_id = $${paramIdx}`);
      params.push(req.user.id);
      paramIdx++;
    } else if (user_id) {
      where.push(`e.user_id = $${paramIdx}`);
      params.push(user_id);
      paramIdx++;
    }

    if (status) {
      where.push(`e.status = $${paramIdx}`);
      params.push(status);
      paramIdx++;
    }
    if (team_id) {
      where.push(`e.team_id = $${paramIdx}`);
      params.push(team_id);
      paramIdx++;
    }

    const whereClause = where.length > 0 ? `WHERE ${where.join(' AND ')}` : '';

    const countResult = await queryOne(
      `SELECT COUNT(*) as count FROM evaluations e ${whereClause}`, params
    );
    const total = parseInt(countResult.count);

    const evaluations = await queryAll(
      `SELECT e.*, t.team_code, t.team_name, t.organization, t.category,
        u.full_name as judge_name, u.judge_id
       FROM evaluations e
       JOIN teams t ON e.team_id = t.id
       JOIN users u ON e.user_id = u.id
       ${whereClause}
       ORDER BY e.updated_at DESC
       LIMIT $${paramIdx} OFFSET $${paramIdx + 1}`,
      [...params, safeLimit, offset]
    );

    res.json({
      evaluations,
      pagination: paginationMeta(total, safePage, safeLimit),
    });
  } catch (error) {
    console.error('List evaluations error:', error);
    res.status(500).json({ error: 'Failed to list evaluations', code: 'INTERNAL_ERROR' });
  }
});

/**
 * GET /api/evaluations/team/:teamId
 * Get all evaluations for a specific team (admin only)
 * Aggregates are computed authoritatively in PostgreSQL (v_team_score_aggregates)
 */
router.get('/team/:teamId', authenticate, requireAdmin, async (req, res) => {
  try {
    const team = await queryOne('SELECT * FROM teams WHERE id = $1', [req.params.teamId]);
    if (!team) {
      return res.status(404).json({ error: 'Team not found', code: 'NOT_FOUND' });
    }

    const evaluations = await queryAll(
      `SELECT e.*, u.full_name as judge_name, u.judge_id
       FROM evaluations e
       JOIN users u ON e.user_id = u.id
       WHERE e.team_id = $1
       ORDER BY e.submitted_at DESC NULLS LAST`,
      [req.params.teamId]
    );

    // Get scores for each evaluation
    for (const eval_ of evaluations) {
      eval_.scores = await queryAll(
        `SELECT es.*, sc.name as criteria_name, sc.max_score, sc.weight, sc.sort_order
         FROM evaluation_scores es
         JOIN scoring_criteria sc ON (COALESCE(es.criteria_id, es.criterion_id) = sc.id)
         WHERE es.evaluation_id = $1
         ORDER BY sc.sort_order`,
        [eval_.id]
      );
    }

    // Authoritative PostgreSQL statistics
    const teamAgg = await getTeamScores(team.id);

    const stats = {
      totalJudges: evaluations.length,
      completedJudges: parseInt(teamAgg?.completed_judges || 0),
      averageScore: teamAgg?.aggregate_score !== null && teamAgg?.aggregate_score !== undefined ? parseFloat(teamAgg.aggregate_score).toFixed(2) : null,
      weightedAverageScore: teamAgg?.weighted_aggregate_score !== null && teamAgg?.weighted_aggregate_score !== undefined ? parseFloat(teamAgg.weighted_aggregate_score).toFixed(2) : null,
      highestScore: teamAgg?.highest_score !== null && teamAgg?.highest_score !== undefined ? parseFloat(teamAgg.highest_score).toFixed(2) : null,
      lowestScore: teamAgg?.lowest_score !== null && teamAgg?.lowest_score !== undefined ? parseFloat(teamAgg.lowest_score).toFixed(2) : null,
    };

    res.json({ team, evaluations, stats });
  } catch (error) {
    console.error('Get team evaluations error:', error);
    res.status(500).json({ error: 'Failed to get evaluations', code: 'INTERNAL_ERROR' });
  }
});

/**
 * GET /api/evaluations/:id
 */
router.get('/:id', authenticate, requireAny, async (req, res) => {
  try {
    const evaluation = await queryOne(
      `SELECT e.*, t.team_code, t.team_name, t.problem_statement_id, t.problem_statement_title,
        t.organization, t.category, t.track, t.team_leader, t.team_members,
        u.full_name as judge_name, u.judge_id
       FROM evaluations e
       JOIN teams t ON e.team_id = t.id
       JOIN users u ON e.user_id = u.id
       WHERE e.id = $1`,
      [req.params.id]
    );

    if (!evaluation) {
      return res.status(404).json({ error: 'Evaluation not found', code: 'NOT_FOUND' });
    }

    // Jury can only see own evaluations
    if (req.user.role === 'JURY' && evaluation.user_id !== req.user.id) {
      return res.status(403).json({ error: 'Access denied', code: 'FORBIDDEN' });
    }

    const scores = await queryAll(
      `SELECT es.*, sc.name as criteria_name, sc.description as criteria_description,
        sc.max_score, sc.weight, sc.sort_order
       FROM evaluation_scores es
       JOIN scoring_criteria sc ON (COALESCE(es.criteria_id, es.criterion_id) = sc.id)
       WHERE es.evaluation_id = $1
       ORDER BY sc.sort_order`,
      [req.params.id]
    );

    evaluation.scores = scores;
    res.json({ evaluation });
  } catch (error) {
    console.error('Get evaluation error:', error);
    res.status(500).json({ error: 'Failed to get evaluation', code: 'INTERNAL_ERROR' });
  }
});

/**
 * POST /api/evaluations
 * Create or get existing draft evaluation for team+jury pair
 */
router.post('/', authenticate, requireAny, async (req, res) => {
  try {
    const { team_id } = req.body;
    const userId = req.user.id;

    if (!team_id) {
      return res.status(400).json({ error: 'team_id is required', code: 'VALIDATION_ERROR' });
    }

    // Verify team exists
    const team = await queryOne('SELECT * FROM teams WHERE id = $1', [team_id]);
    if (!team) {
      return res.status(404).json({ error: 'Team not found', code: 'NOT_FOUND' });
    }

    // Jury: verify assignment
    if (req.user.role === 'JURY') {
      const assignment = await queryOne(
        'SELECT id FROM jury_assignments WHERE user_id = $1 AND team_id = $2',
        [userId, team_id]
      );
      if (!assignment) {
        return res.status(403).json({ error: 'This team is not assigned to you', code: 'NOT_ASSIGNED' });
      }
    }

    // Check for existing evaluation
    let evaluation = await queryOne(
      'SELECT * FROM evaluations WHERE team_id = $1 AND user_id = $2',
      [team_id, userId]
    );

    if (evaluation) {
      // Return existing with scores
      const scores = await queryAll(
        `SELECT es.*, sc.name as criteria_name, sc.description as criteria_description,
          sc.max_score, sc.weight, sc.sort_order
         FROM evaluation_scores es
         JOIN scoring_criteria sc ON (COALESCE(es.criteria_id, es.criterion_id) = sc.id)
         WHERE es.evaluation_id = $1
         ORDER BY sc.sort_order`,
        [evaluation.id]
      );
      evaluation.scores = scores;
      return res.json({ evaluation, isExisting: true });
    }

    // Create new draft
    evaluation = await queryOne(
      'INSERT INTO evaluations (team_id, user_id, status) VALUES ($1, $2, \'draft\') RETURNING *',
      [team_id, userId]
    );

    // Initialize with all active criteria
    const criteria = await queryAll('SELECT id FROM scoring_criteria WHERE is_active = true ORDER BY sort_order');
    for (const c of criteria) {
      await query(
        `INSERT INTO evaluation_scores (evaluation_id, criteria_id, criterion_id, team_id, judge_id)
         VALUES ($1, $2, $2, $3, $4)
         ON CONFLICT (evaluation_id, criteria_id) DO NOTHING`,
        [evaluation.id, c.id, team_id, userId]
      );
    }

    // Fetch with full score data
    const scores = await queryAll(
      `SELECT es.*, sc.name as criteria_name, sc.description as criteria_description,
        sc.max_score, sc.weight, sc.sort_order
       FROM evaluation_scores es
       JOIN scoring_criteria sc ON (COALESCE(es.criteria_id, es.criterion_id) = sc.id)
       WHERE es.evaluation_id = $1
       ORDER BY sc.sort_order`,
      [evaluation.id]
    );
    evaluation.scores = scores;

    await logAction(userId, 'evaluation.created', 'evaluation', evaluation.id,
      { team_code: team.team_code }, getClientIp(req));

    res.status(201).json({ evaluation, isExisting: false });
  } catch (error) {
    console.error('Create evaluation error:', error);
    res.status(500).json({ error: 'Failed to create evaluation', code: 'INTERNAL_ERROR' });
  }
});

/**
 * PUT /api/evaluations/:id
 * Save / autosave draft scores
 * Authoritatively calculated by PostgreSQL inside a transaction
 */
router.put('/:id', authenticate, requireAny, async (req, res) => {
  try {
    const updated = await saveEvaluationScores(
      req.params.id,
      req.body.scores,
      req.body.comments,
      req.user
    );
    res.json({ evaluation: updated, message: 'Draft scores saved successfully' });
  } catch (error) {
    console.error('Update evaluation error:', error);
    res.status(error.status || 500).json({
      error: error.message || 'Failed to update evaluation',
      code: error.code || 'INTERNAL_ERROR',
      field: error.field,
    });
  }
});

/**
 * POST /api/evaluations/:id/submit
 * Finalize and submit evaluation
 * Validates scores, locks evaluation, preserves history snapshot, and recalculates team aggregates
 */
router.post('/:id/submit', authenticate, requireAny, async (req, res) => {
  try {
    const result = await submitEvaluation(req.params.id, req.user, getClientIp(req));
    res.json({
      evaluation: result.evaluation,
      teamStats: result.teamStats,
      message: 'Evaluation submitted successfully',
    });
  } catch (error) {
    console.error('Submit evaluation error:', error);
    res.status(error.status || 500).json({
      error: error.message || 'Failed to submit evaluation',
      code: error.code || 'INTERNAL_ERROR',
      missing: error.missing,
    });
  }
});

/**
 * POST /api/evaluations/:id/reopen
 * Admin reopens a submitted evaluation
 * Preserves audit history snapshot, unlocks evaluation, and recalculates aggregates
 */
router.post('/:id/reopen', authenticate, requireAdmin, async (req, res) => {
  try {
    const result = await reopenEvaluation(req.params.id, req.user, req.body.reason, getClientIp(req));
    res.json({
      evaluation: result.evaluation,
      teamStats: result.teamStats,
      message: 'Evaluation reopened successfully',
    });
  } catch (error) {
    console.error('Reopen evaluation error:', error);
    res.status(error.status || 500).json({
      error: error.message || 'Failed to reopen evaluation',
      code: error.code || 'INTERNAL_ERROR',
    });
  }
});

export default router;
